### PR TITLE
Hotfix MRZ improvement

### PR DESCRIPTION
**Pull request by nicholemnl**
## Issue
#134 MRZ Improvement

## Changes

1. Improve scanning with mrz by fixing the setResolution to 640x480
2. Improve cropping by guide bounding box
3. Add API config option to show guide bounding box

### CODE REVIEW

**Comment by jeremi** [comment]
Why does setting the image size to 640x480 improve the reading of the MRZ?

**Comment by nicholemnl** [comment]
> Why does setting the image size to 640x480 improve the reading of the MRZ?

- Having an incorrect resolution makes the scanned image blur or pixilated simply because it tries to match the size forcefully.
- By default it captured a landscape image meaning the width should be wider than its height
- the PreviewView default is FILL_CENTER, meaning it will try to fill the entire PreviewView which is “landscape” (mention above)
https://developer.android.com/reference/androidx/camera/view/PreviewView.ScaleType#FILL_CENTER

- For evidence, I have attached a comparison between two scanned image 480x640 vs 640x480

**Comment by nicholemnl** [comment]
This would also resolves newlogic/smartscanner-core/issues/133

**Comment by jeremi** [comment]
@nicholemnl should this still be merged?

**Comment by nicholemnl** [comment]
> 

Yes im gonna merge it now.

**Pull request merged**
